### ISSUE TITLE
[CLOSED] People Groups

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#175]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ChrisChasm](https://github.com/ChrisChasm)**
_Friday Jun 30, 2017 at 03:25 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/89_

----

```
linear and non-linear progression for a UUPG becoming a PG?
pre-engagement
people group is defined 
location, language, scripture availability, current engagement level
extraordinary prayer defined and started
worker(s) identified for role(s)
funding determined and obtained
engagement
worker(s) get first access
worker(s) in residence
research is officially accepted
language barriers overcome
scripture access
scripture in trade language(s)
scripture in heart language
Gospel sowing begins
fruit and multiplication 
generational believers
generational churches

desired data fields
worker role(s) for leadership hierarchy (seems like we may need at least 3 levels, maybe more) 
Name of UUPG as in our original (FTT) list
Name of UUPG (endonym) in Roman script
Name of UUPG (endonym) in other scripts
JoshuaProject data access through API
customized description of PG
ROP code
people ID
people group name
primarily language
secondary languages
Bible status
primary religion
primary occupations
% adherent
% evangelical
population 
totals by various areas (country, state, county, city, village, etc.) 
affinity bloc
people cluster
region code
region name
continent
10/40 Window (y/n)
latitude/longitude / GPS location(s)
do we have to let users tell us establish the appropriate vocabulary for the areas descriptors they use (country, state, county, district, province, city, village, neighborhood, etc.) AND mark on maps? 
seems like there is a need for pinpoint coordinates (for a specific individual, for example) and area coordinates (the range of coordinates that would correspond to a whole country, a whole state, a whole city, etc.)
elevations
workers min
workers max
Joshua Project link
PeopleGroups.org link
Finishing the Task link
pictures
Misc pics
Adult male
Adult female
Senior male
Senior female
Male child
Female child
video
misc
livelihood
location
people```

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Thursday Jul 27, 2017 at 16:35 GMT_

----

[Joshua Project API](https://joshuaproject.net/api/v2/people_groups?ROG3=YM&LeastReached=Y&api_key=aWye9lV20QtF)

[api-v2-samples.pdf](https://github.com/ChasmSolutions/disciple-tools/files/1180633/api-v2-samples.pdf)

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Saturday Jul 29, 2017 at 15:34 GMT_

----

Joshua project import and install complete.
- [ ] memory error on large countries (I.e. USA)

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Saturday Jul 29, 2017 at 15:35 GMT_

----


https://github.com/ChasmSolutions/disciple-tools/pull/114

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Monday Jul 31, 2017 at 19:42 GMT_

----

- [x] Make a decision on how much information to story locally
- [x] Make a search and install for individual people groups from Joshua Project.
- [x] Figure out what is the cross reference fields between CPPI, JP, and WCD

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Monday Jul 31, 2017 at 19:47 GMT_

----

Trying to figure out how to use the [ArcGIS](https://api.imb.org/arcgis/rest/services), but having no luck. Might need more coffee. But I would love 30 minutes with someone who is actually using this thing.

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Monday Jul 31, 2017 at 20:18 GMT_

----

I'm closing this task. The people groups has a path to be installed through Joshua Project data through their API. The CPPI and ArcGIS is so unfriendly to use, I'm not sure where to start or if it is even necessary.  

I think there is enough philosophy work left on this piece, I'm closing the task and leaving the section with the current functionality until we circle back to it.
