### ISSUE TITLE
[CLOSED] Groups: Add leader checkbox to member list

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#188]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ChrisChasm](https://github.com/ChrisChasm)**
_Tuesday Jul 25, 2017 at 16:07 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/102_

----

This way we can indicate which people are leaders of the group.

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Wednesday Jul 26, 2017 at 15:54 GMT_

----

- Member (default)
- Leader

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Friday Jul 28, 2017 at 13:45 GMT_

----

- [x]  Remove P2P meta 'unbelieving, etc'
- [x]  Add leadership indicator to p2p
- [x]  Change meta box 4 fields to read from contact not from p2p info.

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Monday Jul 31, 2017 at 13:52 GMT_

----

All has been updated. [Commit](https://github.com/ChasmSolutions/disciple-tools/pull/115)
