### ISSUE TITLE
[CLOSED] Location Upgrade Path

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#196]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ChrisChasm](https://github.com/ChrisChasm)**
_Thursday Jul 27, 2017 at 16:33 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/110_

----

We need to create a progress strategy for a project to have a large area set of locations (i.e. state level) and then later in the project be able to subdivide and work at lower administrative district level (i.e. county or tract level).

So we need to build the ability for upgrades.

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Thursday Jul 27, 2017 at 16:33 GMT_

----

We might consider installing all locations in a progression, so that even if you want to go straight to the county level, you have to go through the state level installation.

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Monday Jul 31, 2017 at 21:05 GMT_

----

- [x] Create Admin 1 and Admin 2 levels for USA, Morocco, Tunisia
  - [x] Admin 1 USA
  - [x] Admin 2 USA
- [x] Host them on S3
- [x] Upload Omega Zones to S3
- [x] Rebuild import scripts to use $wpdb
- [x] Change locations to be hierarchical 
- [x] Build install wizard that starts with highest admin area and works down to lowest.

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Tuesday Aug 01, 2017 at 14:28 GMT_

----

[Consolidated the locations functions](https://github.com/ChasmSolutions/disciple-tools/commit/b91863ee923bb9036e9bfa8effe67546d79a9b6e)

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Wednesday Aug 02, 2017 at 22:54 GMT_

----

There is a lot of work going on right now with normalizing area definitions. We can build a model on what is planned,but will have to update the records once they finish their work. @JustinLong

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Friday Aug 04, 2017 at 18:08 GMT_

----

Install script built. Now creating insert scripts.

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Friday Aug 18, 2017 at 11:28 GMT_

----

This movement mapping project is the outcome of this effort. It will provide a stable api and buffer for the mapping sources. 
https://github.com/ChasmSolutions/movement-mapping

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Tuesday Aug 29, 2017 at 11:46 GMT_

----

After a very long effort. We are pausing further dev into coordinating the locations and mapping. So much of the organization and resources needed to tie into the mapping is not available. There is so much work left to do with the mapping on the ground, that we have just done a version for the US and for T. So this will have to be closed and reopened later when we can push it further down the track.
