### ISSUE TITLE
Create an admin side UI for going through the setup wizard

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-theme#2607]
## Intro
* The aim is to make a hookable setup wizard, where new use cases can easily be added in, and new fields also.
* It would be nice if other plugins could borrow the setup wizard for using once they have been installed.

## Todo

- [x] Build components for use in wizard
  - [x] Fields
  - [x] buttons
  - [x] Selectable items
  - [x] Stepper
  - [x] Breadcrumbs for stepper
- [x] API for getting available steps
- [x] Create front end pieces
  - [x] module selection
  - [x] plugin selection
  - [ ] <s>site options</s>
  - [x] mapbox key
- [x] Intro
- [x] Celebration

## what's left

- [x] Ability to skip steps
- [x] Ability to skip wizard
- [x] Wizard opens in noheader mode on first load of DT and never again
- [x] Remove from admin tab
- [x] remove from admin dashboard when it's done
- [ ] <s>use translations throughout (in steps and in controls)</s>
- [x] only run setup wizard on new instances (add a migration to turn setup wizard off for existing instances)
- [x] add setup wizard to todo steps on dashboard
- [x] add stepper dots
- [x] loading spinner in next button throughout
- [x] celebrate each step where work is done
- [x] optional people group installing step?
- [x] center and limit width for larger screens
- [x] rename all the wizards (harry, hermione, dumbledore)
